### ISSUE TITLE
Doesn't highlight dsGetString or any other dsGet type.

### ISSUE THREAD

**Issue by Andrew-Eathan** [NickMBR/E2-Syntax-Highlight-NPP#1]
Noticed this while coding in notepad++ with the syntax highlighter set to expression2.
![image](https://user-images.githubusercontent.com/42521608/45443158-94277e80-b6cc-11e8-9362-c5e2701b88ff.png)

Doesn't seem to work with other dsGet types either:
![image](https://user-images.githubusercontent.com/42521608/45443277-d9e44700-b6cc-11e8-92ff-0f1ae9af06fc.png)

**Comment by NickMBR** [comment]
@Andrew-Eathan Nice catch! It was unlisted in the official docs. Just included in [df9ef18a201322bee42f0816350119713a72527d](https://github.com/NickMBR/E2-Syntax-Highlight-NPP/commit/df9ef18a201322bee42f0816350119713a72527d)

Thanks!

**Comment by Andrew-Eathan** [comment]
no problem.
